apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-w7qf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-w7qf
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-w7qf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-w7qf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-w7qf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ucri-tenant/status-quarkus-io/statusquarkusio-w7qf@sha256:f3c8b90d6953866d64100867d3015d79edefef02e9c00b338fbcf4494453995e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
